#!/usr/bin/env python3
"""Writes mappings/native-instruments-maschine-mikro-mk2.toml.

The Mikro MK2 has 16 pads with several layers each (step mode, pad mode and
every held button); writing those bindings by hand invites mistakes, so they
are generated here. Run from the repository root:

    python3 scripts/gen-maschine-mikro-mk2.py
"""

from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "mappings" / "native-instruments-maschine-mikro-mk2.toml"

# --- The device ------------------------------------------------------------

# Button notes: bit b of button byte j (report 0x01, bytes 1-4) is note 8j+b.
B = {
    "shift": 0, "erase": 1, "rec": 2, "play": 3, "grid": 4, "step_right": 5, "step_left": 6, "restart": 7,
    "encoder": 11, "note_repeat": 12, "sampling": 13, "browse": 14, "group": 15,
    "main": 16, "right": 17, "left": 18, "nav": 19, "control": 20, "f3": 21, "f2": 22, "f1": 23,
    "mute": 24, "solo": 25, "select": 26, "duplicate": 27, "view": 28, "pad_mode": 29, "pattern": 30, "scene": 31,
}

# LED bytes of output report 0x80 (byte 0 is the report ID). Bytes 9-11 are
# GROUP's RGB LED, the pads follow from byte 31, three bytes each, top-left
# pad first.
LED = {
    "f1": 1, "f2": 2, "f3": 3, "control": 4, "nav": 5, "left": 6, "right": 7, "main": 8,
    "browse": 12, "sampling": 13, "note_repeat": 14, "restart": 15, "step_left": 16, "step_right": 17,
    "grid": 18, "play": 19, "rec": 20, "erase": 21, "shift": 22, "scene": 23, "pattern": 24, "pad_mode": 25,
    "view": 26, "duplicate": 27, "select": 28, "solo": 29, "mute": 30,
}

ENCODER_CC = 64
PAD_NOTE = 64


def pad_number(pos):
    """The number printed on the pad at position `pos` (0 = top left, row by
    row): 1 is bottom left, 16 top right."""
    return (3 - pos // 4) * 4 + pos % 4 + 1


def pad_input(pos):
    """The note of the pad at `pos`: the device numbers pads like their LEDs,
    top left first (pads 13, 9, 5, 1 down the left are 0, 4, 8, 12)."""
    return PAD_NOTE + pos


# Pad colours (rille_core::remix::led_code): 1 + colour index, + 0x20 bright.
def code(color, bright):
    return (color + 1) | (0x20 if bright else 0)


WHITE, RED, YELLOW, GREEN, SKY = 0, 1, 4, 6, 9

# What SHIFT + pad does, by printed pad number: target, step (relative, or
# ("set", value) for a fixed value) and colour of the pad.
SHIFT = {
    1: ("drum.undo", None, WHITE),
    2: ("drum.redo", None, WHITE),
    3: ("drum.undo", None, WHITE),
    4: ("drum.redo", None, WHITE),
    # The steps are on the grid already: QUANTIZE straightens the swing,
    # QUANT 50% sets half of it.
    5: ("drum.swing", ("set", 0.0), SKY),
    6: ("drum.swing", ("set", 0.5), SKY),
    7: ("drum.nudge", -1, SKY),
    8: ("drum.nudge", 1, SKY),
    9: ("drum.clear", None, RED),
    10: ("drum.clear_pattern", None, RED),
    11: ("drum.copy", None, GREEN),
    12: ("drum.paste", None, GREEN),
    13: ("drum.sel_tune", -1 / 24, YELLOW),
    14: ("drum.sel_tune", 1 / 24, YELLOW),
    15: ("drum.sel_tune", -0.5, YELLOW),
    16: ("drum.sel_tune", 0.5, YELLOW),
}

# --- Writing ---------------------------------------------------------------

out = []


def emit(s=""):
    out.append(s)


def num(v):
    return repr(round(v, 6))


def inp(target, note=None, cc=None, condition=None, **extra):
    emit("[[input]]")
    emit(f'target = "{target}"')
    if note is not None:
        emit(f'midi = {{ type = "note", channel = 1, number = {note} }}')
    else:
        emit(f'midi = {{ type = "cc", channel = 1, number = {cc} }}')
    for k, v in extra.items():
        if isinstance(v, bool):
            emit(f"{k} = {'true' if v else 'false'}")
        elif isinstance(v, (int, float)):
            emit(f"{k} = {num(v)}")
        else:
            emit(f'{k} = "{v}"')
    if condition:
        emit(f'condition = {{ modifier = "{condition}" }}')
    emit()


def outp(source, channel, number, condition=None, raw=False, on=None, off=None):
    emit("[[output]]")
    emit(f'source = "{source}"')
    emit(f'midi = {{ type = "note", channel = {channel}, number = {number} }}')
    if raw:
        emit("raw = true")
    if on is not None:
        emit(f"on = {on}")
    if off is not None:
        emit(f"off = {off}")
    if condition:
        emit(f'condition = {{ modifier = "{condition}" }}')
    emit()


HEADER = '''\
# Native Instruments Maschine Mikro MK2
#
# GENERATED by scripts/gen-maschine-mikro-mk2.py; change the script, not
# this file.
#
# The Mikro MK2 is a HID device, not MIDI: rille reads its reports as
# described in the [hid] table below (see crates/rille-midi/src/hid.rs) and
# presents them as MIDI on channel 1. On Linux it needs the udev rule in
# packaging/udev/70-rille-controllers.rules.
#
# The Mikro drives the drum machine; it works next to any DJ controller.
# Pads are numbered as printed (1 bottom left … 16 top right); steps,
# patterns, lengths and kits count from the top left, row by row, like the
# steps on screen. Instruments are on the top two rows: A-H as printed =
# BD SD CH OH / CP RS LT CY.
#
#   PADS (STEP MODE)    steps 1-16 of the selected instrument; a hard hit
#                       sets an accent
#   PAD MODE            pads play the instruments (top rows, with velocity;
#                       recorded while REC is on) and mute them (bottom rows,
#                       below each instrument); again: back to step mode
#   SHIFT+GROUP         STEP MODE
#   held, then a pad:
#     GROUP / SELECT    select the instrument
#     MUTE / SOLO       mute / solo the instrument
#     ERASE             clear the instrument's steps (SHIFT+ERASE: the pattern)
#     SAMPLING          load the track selected in the library as the
#                       instrument's sound (a tap on SAMPLING: drums in the
#                       headphones)
#     PATTERN           pattern 1-16, from the next bar while playing
#                       (tap PATTERN to keep it up, tap again to leave)
#     DUPLICATE         copy the pattern to 1-16
#     GRID              pattern length 1-16
#     SCENE             kit 1-16 (factory kits first)
#     NOTE REPEAT       rolls on the clock while a pad is held (tap NOTE
#                       REPEAT to keep it on); the encoder sets the rate
#     SHIFT             as printed: UNDO, REDO, NUDGE < >, CLEAR (the
#                       instrument), CLR AUTO (the pattern), COPY, PASTE,
#                       SEMITONE - +, OCTAVE - + (tune of the instrument),
#                       QUANTIZE (straight: no swing), QUANT 50% (half swing)
#   PLAY                start/stop, in time with the master clock
#   RESTART             start on the next downbeat / stop at the end of the bar
#   REC                 live recording; SHIFT+REC (COUNT-IN): from the next
#                       downbeat; ERASE+REC (REPLACE, lit on ERASE): the first
#                       hit of an instrument clears its old steps
#   < STEP / STEP >     previous/next pattern
#   < / > (display)     previous/next instrument
#   ENCODER             what the lit button chose: F1 level, F2 tune, F3 decay
#                       (selected instrument), CONTROL filter, MAIN or
#                       SHIFT+VIEW volume (drum channel); SHIFT+encoder swing.
#                       While PATTERN, GRID, NOTE REPEAT, BROWSE or
#                       GROUP/SELECT is held it chooses pattern, length, rate,
#                       kit or instrument. Push: back to the default value.
#   VIEW                show/hide the drum machine
#   NAV                 drums through FX 1 (SHIFT: FX 2)
#   SHIFT+MUTE          CHOKE: closed hi-hat cuts the open one
#
# The display shows pattern, transport, instrument, tempo, all steps with
# the playhead, and the encoder's target; held buttons show their pads.

name = "Native Instruments Maschine Mikro MK2"
device = '(?i)maschine mikro mk2 hid'
description = "Native Instruments Maschine Mikro MK2 (HID): the drum machine on 16 pressure pads with a display"

# Report layout. Byte offsets count the report ID as byte 0.
[hid]
name = "Maschine Mikro MK2"
vendor_id = 0x17cc
product_id = 0x1200
input_report = 0x01
buttons = [0x01, 4]
encoders = [{ offset = 0x05, bits = 4, cc = 64, note = 48 }]
outputs = [[0x80, 79]]
# Pads from byte 31 (top left first), then GROUP's LED as pad 17. The red
# and blue LEDs are stronger than the green ones.
rgb_pads = { offset = 31, count = 16, order = [0, 1, 2], extra = [9], balance = [0.55, 1.0, 0.75] }
pressure_pads = { report = 0x20, offset = 1, count = 32, note = 64, on = 300, off = 150, max = 3900 }
bitmap = { report = 0xE0, width = 128, height = 64, chunk_pages = 2, screen = "drum" }
'''


def main():
    emit(HEADER)

    emit("# --- Modifiers ---------------------------------------------------------\n")
    for m in ["shift", "erase", "grid", "group", "select", "mute", "solo", "duplicate", "scene", "browse", "sampling"]:
        inp(f"modifier:{m}", note=B[m])
    for m in ["pattern", "note_repeat"]:
        inp(f"modifier:{m}", note=B[m], latch=True, hold=True)
    # Pad mode: step (the default) or play.
    inp("modifier:play", note=B["pad_mode"], latch=True, group="pads")
    inp("modifier:step", note=B["group"], condition="shift", latch=True, group="pads", default=True)
    # What the encoder edits.
    for m, button, cond, default in [
        ("enc_filter", "control", None, True),
        ("enc_level", "f1", None, False),
        ("enc_tune", "f2", None, False),
        ("enc_decay", "f3", None, False),
        ("enc_volume", "main", None, False),
        ("enc_volume", "view", "shift", False),
    ]:
        extra = {"latch": True, "group": "enc"}
        if default:
            extra["default"] = True
        inp(f"modifier:{m}", note=B[button], condition=cond, **extra)

    emit("# --- Buttons -----------------------------------------------------------\n")
    inp("drum.play", note=B["play"])
    inp("drum.play_bar", note=B["restart"])
    inp("drum.record", note=B["rec"])
    inp("drum.count_in", note=B["rec"], condition="shift")
    inp("drum.replace", note=B["rec"], condition="erase")
    inp("drum.clear_pattern", note=B["erase"], condition="shift")
    inp("drum.choke", note=B["mute"], condition="shift")
    inp("drum.pattern_select", note=B["step_left"], step=-1)
    inp("drum.pattern_select", note=B["step_right"], step=1)
    inp("drum.inst_select", note=B["left"], step=-1)
    inp("drum.inst_select", note=B["right"], step=1)
    inp("drum.show", note=B["view"])
    inp("drum.fx_assign.1", note=B["nav"])
    inp("drum.fx_assign.2", note=B["nav"], condition="shift")
    # A tap: drums in the headphones; held with a pad: load a sample.
    inp("drum.pfl", note=B["sampling"], tap=True)

    emit("# --- Encoder: turn ----------------------------------------------------\n")
    enc = {"encoding": "twos_complement"}
    inp("drum.filter", cc=ENCODER_CC, mode="relative", step=0.01, **enc)
    # Levels and decay in 1/32 per click: 1 % steps on the quadratic fader
    # curve could hardly be heard, and silencing a track took many turns.
    for m, target, step in [
        ("enc_level", "drum.sel_level", 1 / 32),
        ("enc_tune", "drum.sel_tune", 1 / 48),
        ("enc_decay", "drum.sel_decay", 1 / 32),
        ("enc_volume", "drum.level", 1 / 32),
    ]:
        inp(target, cc=ENCODER_CC, condition=m, mode="relative", step=step, **enc)
    inp("drum.swing", cc=ENCODER_CC, condition="shift", mode="relative", step=0.01, **enc)
    for m, target in [
        ("pattern", "drum.pattern_select"),
        ("duplicate", "drum.pattern_select"),
        ("grid", "drum.length"),
        ("note_repeat", "drum.repeat_rate"),
        ("browse", "drum.kit_select"),
        ("scene", "drum.kit_select"),
        ("group", "drum.inst_select"),
        ("select", "drum.inst_select"),
    ]:
        inp(target, cc=ENCODER_CC, condition=m, step=0.5, **enc)

    emit("# --- Encoder: push (back to the default) -------------------------------\n")
    inp("drum.filter", note=B["encoder"], set=0.5)
    for m, target, v in [
        ("enc_level", "drum.sel_level", 1.0),
        ("enc_tune", "drum.sel_tune", 0.5),
        ("enc_decay", "drum.sel_decay", 1.0),
        ("enc_volume", "drum.level", 0.8),
        ("shift", "drum.swing", 0.0),
    ]:
        inp(target, note=B["encoder"], condition=m, set=v)

    emit("# --- Pads --------------------------------------------------------------\n")
    for pos in range(16):
        n, note = pos + 1, pad_input(pos)
        top = pos < 8  # the instrument rows
        inst = pos + 1 if top else pos - 7
        emit(f"# Pad {pad_number(pos)} (position {n})")
        inp(f"drum.step.{n}", note=note, mode="velocity")
        if top:
            inp(f"drum.trigger.{inst}", note=note, condition="play", mode="velocity")
            inp(f"drum.repeat.{inst}", note=note, condition="note_repeat", mode="velocity")
            for m, target in [
                ("group", "inst"),
                ("select", "inst"),
                ("mute", "inst_mute"),
                ("solo", "inst_solo"),
                ("erase", "inst_clear"),
                ("sampling", "load_selected"),
            ]:
                inp(f"drum.{target}.{inst}", note=note, condition=m)
        else:
            inp(f"drum.inst_mute.{inst}", note=note, condition="play")
            inp(f"drum.inst_mute.{inst}", note=note, condition="note_repeat")
        inp(f"drum.pattern.{n}", note=note, condition="pattern")
        inp(f"drum.pattern_copy.{n}", note=note, condition="duplicate")
        inp(f"drum.length_set.{n}", note=note, condition="grid")
        inp(f"drum.kit.{n}", note=note, condition="scene")
        shift = SHIFT.get(pad_number(pos))
        if shift:
            target, step, _ = shift
            if step is None:
                inp(target, note=note, condition="shift")
            elif isinstance(step, tuple):
                inp(target, note=note, condition="shift", set=step[1])
            else:
                inp(target, note=note, condition="shift", mode="relative", step=step)

    emit("# --- Pad LEDs (channel 2: pad = position, value = LED code) ------------\n")
    for pos in range(16):
        n = pos + 1
        top = pos < 8
        inst = pos + 1 if top else pos - 7
        outp(f"drum.step_led.{n}", 2, n, raw=True)
        if top:
            outp(f"drum.trigger_led.{inst}", 2, n, condition="play", raw=True)
            outp(f"drum.trigger_led.{inst}", 2, n, condition="note_repeat", raw=True)
            for m in ["group", "select", "erase", "sampling"]:
                outp(f"drum.inst_led.{inst}", 2, n, condition=m, raw=True)
            for m in ["mute", "solo"]:
                outp(f"drum.mute_led.{inst}", 2, n, condition=m, raw=True)
        else:
            outp(f"drum.mute_led.{inst}", 2, n, condition="play", raw=True)
            outp(f"drum.mute_led.{inst}", 2, n, condition="note_repeat", raw=True)
            # Held instrument layers use the top rows only.
            for m in ["group", "select", "erase", "sampling", "mute", "solo"]:
                outp("drum.copy", 2, n, condition=m, off=0)
        outp(f"drum.pattern_led.{n}", 2, n, condition="pattern", raw=True)
        outp(f"drum.pattern_led.{n}", 2, n, condition="duplicate", raw=True)
        outp(f"drum.length_led.{n}", 2, n, condition="grid", raw=True)
        outp(f"drum.kit_led.{n}", 2, n, condition="scene", raw=True)
        shift = SHIFT.get(pad_number(pos))
        if shift and shift[0] in ("drum.undo", "drum.redo"):
            # Bright while there is something to undo (redo).
            outp(shift[0], 2, n, condition="shift", on=code(shift[2], True), off=code(shift[2], False))
        elif shift:
            outp("drum.copy", 2, n, condition="shift", off=code(shift[2], False))
        else:
            outp("drum.copy", 2, n, condition="shift", off=0)
    # GROUP: the selected instrument's colour.
    outp("drum.sel_led", 2, 17, raw=True)

    emit("# --- Button LEDs (channel 1: note = LED byte), dim when off ------------\n")
    for source, led in [
        ("modifier:enc_level", "f1"),
        ("modifier:enc_tune", "f2"),
        ("modifier:enc_decay", "f3"),
        ("modifier:enc_filter", "control"),
        ("modifier:enc_volume", "main"),
        ("drum.fx_assign.1", "nav"),
        ("drum.copy", "left"),
        ("drum.copy", "right"),
        ("modifier:browse", "browse"),
        ("drum.pfl", "sampling"),
        ("modifier:note_repeat", "note_repeat"),
        ("drum.play_bar", "restart"),
        ("drum.copy", "step_left"),
        ("drum.copy", "step_right"),
        ("modifier:grid", "grid"),
        ("drum.play", "play"),
        ("drum.record", "rec"),
        ("drum.replace", "erase"),
        ("modifier:shift", "shift"),
        ("modifier:scene", "scene"),
        ("modifier:pattern", "pattern"),
        ("modifier:play", "pad_mode"),
        ("drum.show", "view"),
        ("modifier:duplicate", "duplicate"),
        ("modifier:select", "select"),
        ("modifier:solo", "solo"),
        ("modifier:mute", "mute"),
    ]:
        outp(source, 1, LED[led], off=10)
    # While SHIFT is held, the buttons with a SHIFT function show its state.
    outp("drum.fx_assign.2", 1, LED["nav"], condition="shift", off=10)
    outp("drum.choke", 1, LED["mute"], condition="shift", off=10)
    # Held buttons lit while down, over what their LED shows otherwise.
    outp("modifier:erase", 1, LED["erase"], condition="erase", off=10)
    outp("modifier:sampling", 1, LED["sampling"], condition="sampling", off=10)

    OUT.write_text("\n".join(out).rstrip() + "\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
